課題1の実装,ポケモンデータを表示するカスタムセルの実装
Mako0722/PokeChallenge01 pull request #2
Opened 2022-12-08 08:54 UTC by Mako0722

<h1>・概要</h1>
【xib】【課題1】InterfaceBuilderを使ってカスタムセルを実装
<h1>・やりたいこと</h1>

- [x] No、名前、各ステータスをデザイン通りに表示する

- [x] テキストはUILabelクラスを使用する

- [x] StackViewを使用

- [x] XIBファイルでレイアウトを組む

- [x]  データは既に、Pokemonという命名で用意されているためそれを使用する

- [x] デザインを参考にする
<img width="433" alt="スクリーンショット 2022-12-24 1 09 16" src="https://user-images.githubusercontent.com/68636443/209365407-f1f669ba-4d26-46f7-a6f8-52dea9939347.png">

<img width="785" alt="スクリーンショット 2022-12-24 1 09 42" src="https://user-images.githubusercontent.com/68636443/209365415-e143eb73-5ef7-4d3b-8627-69bcab7482d5.png">

2022-12-08 10:20 UTC, sosuiiii commented
次回からコミット単位は意味のあるまとまりですると良さそうです🙆🏻‍♂️
後からコミット整理したい時に粒度が大きいと不便なので🫡(コミット整理は後々学びましょう！)

2022-12-08 10:25 UTC, sosuiiii commented
StackViewの制約が全体的に怪しそうです
id、nameラベルのStackView
セルのビューに対して制約がかかってしまっています。特にbottomの制約は、ステータス群からnの距離で制約をつけたいですね。
- leadingは良さそうです
- bottomは下のStackViewに対して制約をつけましょう！
- trailingは右から20以上という制約をつけましょう！20以上にしないと、ラベルが長い時に今以上に伸びなくなってしまいます。

他のStackViewも同様に修正してみてください🫡

2022-12-08 10:30 UTC, sosuiiii commented
セルの値にステータスを代入をしている部分ですが、こうげき \(変数)のように間に半角スペースを入れないとダメそうです

2022-12-08 10:31 UTC, sosuiiii commented
IBOutlet接続している変数はprivateにしてあげましょう！UIに関する関心はUIを責務に持つクラス以外から見えてはいけないためです

2022-12-08 10:32 UTC, sosuiiii commented
セルでステータスを代入している部分ですが、スコープの最後に無駄な余白が2行入っているので消してあげましょう🙆🏻‍♂️

2022-12-08 10:35 UTC, sosuiiii commented
セルのクラスに余計な空白行が多く見られるので消してあげてください🙆🏻‍♂️
意味の違うコードの塊であれば最大2行まで
基本1行に抑えたいです

2022-12-09 06:37 UTC, sosuiiii approved these changes

2022-12-09 06:37 UTC, sosuiiii commented on PokeTableViewCell.swift
> +
不要な行なので消すと良いです🙆🏻‍♂️

2022-12-09 06:37 UTC, sosuiiii commented on PokeTableViewCell.swift
> +
awakeFromNibもsetSelectedも使っていないので消すと良いです👀

2022-12-09 06:37 UTC, sosuiiii commented on PokeTableViewCell.swift
> +
不要な行が見られますね👀

2022-12-09 06:37 UTC, sosuiiii commented on PokeTableViewCell.swift
> +
ここの行も不要そうです

2022-12-09 06:37 UTC, sosuiiii commented on PokeTableViewCell.swift
> +
ここの行も不要そうです

2022-12-09 06:37 UTC, sosuiiii commented on PokeTableViewCell.swift
> +
ここの行も不要そうです

2022-12-09 06:38 UTC, sosuiiii requested changes
レビューしました！

2022-12-10 14:07 UTC, techsta-inc requested changes
<img width="414" alt="スクリーンショット 2022-12-10 23 04 29" src="https://user-images.githubusercontent.com/117347788/206859242-6aea1ed8-7a3c-4c11-a52a-1d25fae7b47c.png">
この辺りの制約が怪しいですね  
それ以上はオブジェクトが伸びないことを意味しているので、
名前が長いポケモンだと名前が切れてしまいますし、
bottom + 92 を見る限りセルの枠に対して余白をとっているようです。
セルの枠ではなく、直下にあるUIオブジェクト(下のStackView)に対して余白を設定してあげてください🙌🏻
そうでないと、下にあるStackViewの高さが今後変わったときにレイアウトが崩れそうです

2022-12-10 14:07 UTC, techsta-inc commented on PokeTableViewCell.swift
>      @IBOutlet weak var speedLabel: UILabel!
全てprivate weak var としてあげてください🙆🏻‍♂️
他のクラスから関心を持てるのは副作用になってしまいます

2022-12-10 14:07 UTC, techsta-inc commented on PokeTableViewCell.swift
> +        speedLabel.text = "すばやさ \(pokemon.status.speed)"
同じクラスの修正はコミットを分けない方が良いです🙆🏻‍♂️
コミット順にレビューをする人からすると、対応していないように映る場合があります

2022-12-10 14:09 UTC, techsta-inc commented
修正ができたらこちらのスクリーンショットも張り替えてもらえるとレビューしやすいのでお願いします🙆🏻‍♂️

<img width="756" alt="スクリーンショット 2022-12-10 23 09 18" src="https://user-images.githubusercontent.com/117347788/206859436-095f48c9-01b9-4cd3-a5a3-d889bd3d1e0a.png">

2022-12-12 15:21 UTC, techsta-inc commented
これが隣接したオブジェクトに対しての余白でなさそうなのが気になります👀
<img width="290" alt="スクリーンショット 2022-12-13 0 21 02" src="https://user-images.githubusercontent.com/117347788/207083232-3ffa0718-b39b-44ff-95e7-b428db89c173.png">

2022-12-12 15:23 UTC, techsta-inc commented
あ
<img width="405" alt="スクリーンショット 2022-12-13 0 22 59" src="https://user-images.githubusercontent.com/117347788/207083697-940ef53d-ee0a-49ab-8b65-e0732c9d9061.png">

2022-12-12 15:24 UTC, techsta-inc commented
imageViewのサイズが指定されていないようなので、レクチャーのデザインを確認して制約を追加してあげてください🙆🏻‍♂️

2022-12-12 15:27 UTC, techsta-inc commented
画面の小さい端末だとより文字列の省略が目立ってしまいそうですね👀
[content-hugging-priority](https://grandbig.github.io/blog/2018/08/04/content-hugging-priority/)かもしくは
UILabelのautoshrinkで調べて、これに対応してみてください🙆🏻‍♂️

<img width="342" alt="スクリーンショット 2022-12-13 0 25 37" src="https://user-images.githubusercontent.com/117347788/207084353-63ecb122-cb36-4ce4-95de-91c8db546575.png">

2022-12-25 02:41 UTC, techsta-inc commented on PokeTableViewCell.xib
> +                    <stackView opaque="NO" contentMode="scaleToFill" verticalHuggingPriority="270" horizontalCompressionResistancePriority="770" spacing="8" translatesAutoresizingMaskIntoConstraints=
>verticalHuggingPriority="270" horizontalCompressionResistancePriority="770"

良いですね！huggingやregistanceは今後、デザイナーの細かい要望を実現するために重要な要素なのと
駆け出しの方はこの存在になかなか気づかないので大きな学びだと思います！

2022-12-25 02:42 UTC, techsta-inc approved these changes
レビュワーの、修正後のレイアウト確認の手間を減らすために
正常系と異常系(文字列が長い場合)のスクショを貼っておくととても良きです🙏🏻
お疲れ様です！

2023-01-07 16:47 UTC, merged